typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=false
p10k reload
typeset -g POWERLEVEL9K_IP_INTERFACE='[ew|eth0].*'
typeset -g POWERLEVEL9K_IP_CONTENT_EXPANSION='${P9K_IP_RX_RATE:+⇣$P9K_IP_RX_RATE }${P9K_IP_TX_RATE:+⇡$P9K_IP_TX_RATE }$P9K_IP_IP'
typeset -g POWERLEVEL9K_IP_VISUAL_IDENTIFIER_EXPANSION=$'\uf817'
